// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto
// Protobuf Java Version: 4.26.1

package com.macasaet.fernet.example.pb;

public final class Example {
  private Example() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      Example.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SessionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:example.Session)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string sessionId = 1;</code>
     * @return Whether the sessionId field is set.
     */
    boolean hasSessionId();
    /**
     * <code>required string sessionId = 1;</code>
     * @return The sessionId.
     */
    java.lang.String getSessionId();
    /**
     * <code>required string sessionId = 1;</code>
     * @return The bytes for sessionId.
     */
    com.google.protobuf.ByteString
        getSessionIdBytes();

    /**
     * <code>required int32 renewalCount = 2;</code>
     * @return Whether the renewalCount field is set.
     */
    boolean hasRenewalCount();
    /**
     * <code>required int32 renewalCount = 2;</code>
     * @return The renewalCount.
     */
    int getRenewalCount();

    /**
     * <pre>
     * seconds after the epoch
     * </pre>
     *
     * <code>required int64 startTime = 3;</code>
     * @return Whether the startTime field is set.
     */
    boolean hasStartTime();
    /**
     * <pre>
     * seconds after the epoch
     * </pre>
     *
     * <code>required int64 startTime = 3;</code>
     * @return The startTime.
     */
    long getStartTime();

    /**
     * <pre>
     * seconds after the epoch
     * </pre>
     *
     * <code>optional int64 lastRenewalTime = 4;</code>
     * @return Whether the lastRenewalTime field is set.
     */
    boolean hasLastRenewalTime();
    /**
     * <pre>
     * seconds after the epoch
     * </pre>
     *
     * <code>optional int64 lastRenewalTime = 4;</code>
     * @return The lastRenewalTime.
     */
    long getLastRenewalTime();
  }
  /**
   * Protobuf type {@code example.Session}
   */
  public static final class Session extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:example.Session)
      SessionOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        Session.class.getName());
    }
    // Use Session.newBuilder() to construct.
    private Session(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Session() {
      sessionId_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.macasaet.fernet.example.pb.Example.internal_static_example_Session_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.macasaet.fernet.example.pb.Example.internal_static_example_Session_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.macasaet.fernet.example.pb.Example.Session.class, com.macasaet.fernet.example.pb.Example.Session.Builder.class);
    }

    private int bitField0_;
    public static final int SESSIONID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object sessionId_ = "";
    /**
     * <code>required string sessionId = 1;</code>
     * @return Whether the sessionId field is set.
     */
    @java.lang.Override
    public boolean hasSessionId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string sessionId = 1;</code>
     * @return The sessionId.
     */
    @java.lang.Override
    public java.lang.String getSessionId() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sessionId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string sessionId = 1;</code>
     * @return The bytes for sessionId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RENEWALCOUNT_FIELD_NUMBER = 2;
    private int renewalCount_ = 0;
    /**
     * <code>required int32 renewalCount = 2;</code>
     * @return Whether the renewalCount field is set.
     */
    @java.lang.Override
    public boolean hasRenewalCount() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required int32 renewalCount = 2;</code>
     * @return The renewalCount.
     */
    @java.lang.Override
    public int getRenewalCount() {
      return renewalCount_;
    }

    public static final int STARTTIME_FIELD_NUMBER = 3;
    private long startTime_ = 0L;
    /**
     * <pre>
     * seconds after the epoch
     * </pre>
     *
     * <code>required int64 startTime = 3;</code>
     * @return Whether the startTime field is set.
     */
    @java.lang.Override
    public boolean hasStartTime() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * seconds after the epoch
     * </pre>
     *
     * <code>required int64 startTime = 3;</code>
     * @return The startTime.
     */
    @java.lang.Override
    public long getStartTime() {
      return startTime_;
    }

    public static final int LASTRENEWALTIME_FIELD_NUMBER = 4;
    private long lastRenewalTime_ = 0L;
    /**
     * <pre>
     * seconds after the epoch
     * </pre>
     *
     * <code>optional int64 lastRenewalTime = 4;</code>
     * @return Whether the lastRenewalTime field is set.
     */
    @java.lang.Override
    public boolean hasLastRenewalTime() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * seconds after the epoch
     * </pre>
     *
     * <code>optional int64 lastRenewalTime = 4;</code>
     * @return The lastRenewalTime.
     */
    @java.lang.Override
    public long getLastRenewalTime() {
      return lastRenewalTime_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSessionId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRenewalCount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStartTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, sessionId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, renewalCount_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt64(3, startTime_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt64(4, lastRenewalTime_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, sessionId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, renewalCount_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, startTime_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, lastRenewalTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.macasaet.fernet.example.pb.Example.Session)) {
        return super.equals(obj);
      }
      com.macasaet.fernet.example.pb.Example.Session other = (com.macasaet.fernet.example.pb.Example.Session) obj;

      if (hasSessionId() != other.hasSessionId()) return false;
      if (hasSessionId()) {
        if (!getSessionId()
            .equals(other.getSessionId())) return false;
      }
      if (hasRenewalCount() != other.hasRenewalCount()) return false;
      if (hasRenewalCount()) {
        if (getRenewalCount()
            != other.getRenewalCount()) return false;
      }
      if (hasStartTime() != other.hasStartTime()) return false;
      if (hasStartTime()) {
        if (getStartTime()
            != other.getStartTime()) return false;
      }
      if (hasLastRenewalTime() != other.hasLastRenewalTime()) return false;
      if (hasLastRenewalTime()) {
        if (getLastRenewalTime()
            != other.getLastRenewalTime()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSessionId()) {
        hash = (37 * hash) + SESSIONID_FIELD_NUMBER;
        hash = (53 * hash) + getSessionId().hashCode();
      }
      if (hasRenewalCount()) {
        hash = (37 * hash) + RENEWALCOUNT_FIELD_NUMBER;
        hash = (53 * hash) + getRenewalCount();
      }
      if (hasStartTime()) {
        hash = (37 * hash) + STARTTIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getStartTime());
      }
      if (hasLastRenewalTime()) {
        hash = (37 * hash) + LASTRENEWALTIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getLastRenewalTime());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.macasaet.fernet.example.pb.Example.Session parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.macasaet.fernet.example.pb.Example.Session parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.macasaet.fernet.example.pb.Example.Session parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.macasaet.fernet.example.pb.Example.Session parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.macasaet.fernet.example.pb.Example.Session parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.macasaet.fernet.example.pb.Example.Session parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.macasaet.fernet.example.pb.Example.Session parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.macasaet.fernet.example.pb.Example.Session parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.macasaet.fernet.example.pb.Example.Session parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.macasaet.fernet.example.pb.Example.Session parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.macasaet.fernet.example.pb.Example.Session parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.macasaet.fernet.example.pb.Example.Session parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.macasaet.fernet.example.pb.Example.Session prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code example.Session}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:example.Session)
        com.macasaet.fernet.example.pb.Example.SessionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.macasaet.fernet.example.pb.Example.internal_static_example_Session_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.macasaet.fernet.example.pb.Example.internal_static_example_Session_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.macasaet.fernet.example.pb.Example.Session.class, com.macasaet.fernet.example.pb.Example.Session.Builder.class);
      }

      // Construct using com.macasaet.fernet.example.pb.Example.Session.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        sessionId_ = "";
        renewalCount_ = 0;
        startTime_ = 0L;
        lastRenewalTime_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.macasaet.fernet.example.pb.Example.internal_static_example_Session_descriptor;
      }

      @java.lang.Override
      public com.macasaet.fernet.example.pb.Example.Session getDefaultInstanceForType() {
        return com.macasaet.fernet.example.pb.Example.Session.getDefaultInstance();
      }

      @java.lang.Override
      public com.macasaet.fernet.example.pb.Example.Session build() {
        com.macasaet.fernet.example.pb.Example.Session result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.macasaet.fernet.example.pb.Example.Session buildPartial() {
        com.macasaet.fernet.example.pb.Example.Session result = new com.macasaet.fernet.example.pb.Example.Session(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.macasaet.fernet.example.pb.Example.Session result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.sessionId_ = sessionId_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.renewalCount_ = renewalCount_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.startTime_ = startTime_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.lastRenewalTime_ = lastRenewalTime_;
          to_bitField0_ |= 0x00000008;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.macasaet.fernet.example.pb.Example.Session) {
          return mergeFrom((com.macasaet.fernet.example.pb.Example.Session)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.macasaet.fernet.example.pb.Example.Session other) {
        if (other == com.macasaet.fernet.example.pb.Example.Session.getDefaultInstance()) return this;
        if (other.hasSessionId()) {
          sessionId_ = other.sessionId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasRenewalCount()) {
          setRenewalCount(other.getRenewalCount());
        }
        if (other.hasStartTime()) {
          setStartTime(other.getStartTime());
        }
        if (other.hasLastRenewalTime()) {
          setLastRenewalTime(other.getLastRenewalTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasSessionId()) {
          return false;
        }
        if (!hasRenewalCount()) {
          return false;
        }
        if (!hasStartTime()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                sessionId_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                renewalCount_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                startTime_ = input.readInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                lastRenewalTime_ = input.readInt64();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object sessionId_ = "";
      /**
       * <code>required string sessionId = 1;</code>
       * @return Whether the sessionId field is set.
       */
      public boolean hasSessionId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string sessionId = 1;</code>
       * @return The sessionId.
       */
      public java.lang.String getSessionId() {
        java.lang.Object ref = sessionId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sessionId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string sessionId = 1;</code>
       * @return The bytes for sessionId.
       */
      public com.google.protobuf.ByteString
          getSessionIdBytes() {
        java.lang.Object ref = sessionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sessionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string sessionId = 1;</code>
       * @param value The sessionId to set.
       * @return This builder for chaining.
       */
      public Builder setSessionId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        sessionId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>required string sessionId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSessionId() {
        sessionId_ = getDefaultInstance().getSessionId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>required string sessionId = 1;</code>
       * @param value The bytes for sessionId to set.
       * @return This builder for chaining.
       */
      public Builder setSessionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        sessionId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int renewalCount_ ;
      /**
       * <code>required int32 renewalCount = 2;</code>
       * @return Whether the renewalCount field is set.
       */
      @java.lang.Override
      public boolean hasRenewalCount() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required int32 renewalCount = 2;</code>
       * @return The renewalCount.
       */
      @java.lang.Override
      public int getRenewalCount() {
        return renewalCount_;
      }
      /**
       * <code>required int32 renewalCount = 2;</code>
       * @param value The renewalCount to set.
       * @return This builder for chaining.
       */
      public Builder setRenewalCount(int value) {

        renewalCount_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 renewalCount = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRenewalCount() {
        bitField0_ = (bitField0_ & ~0x00000002);
        renewalCount_ = 0;
        onChanged();
        return this;
      }

      private long startTime_ ;
      /**
       * <pre>
       * seconds after the epoch
       * </pre>
       *
       * <code>required int64 startTime = 3;</code>
       * @return Whether the startTime field is set.
       */
      @java.lang.Override
      public boolean hasStartTime() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       * seconds after the epoch
       * </pre>
       *
       * <code>required int64 startTime = 3;</code>
       * @return The startTime.
       */
      @java.lang.Override
      public long getStartTime() {
        return startTime_;
      }
      /**
       * <pre>
       * seconds after the epoch
       * </pre>
       *
       * <code>required int64 startTime = 3;</code>
       * @param value The startTime to set.
       * @return This builder for chaining.
       */
      public Builder setStartTime(long value) {

        startTime_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * seconds after the epoch
       * </pre>
       *
       * <code>required int64 startTime = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearStartTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        startTime_ = 0L;
        onChanged();
        return this;
      }

      private long lastRenewalTime_ ;
      /**
       * <pre>
       * seconds after the epoch
       * </pre>
       *
       * <code>optional int64 lastRenewalTime = 4;</code>
       * @return Whether the lastRenewalTime field is set.
       */
      @java.lang.Override
      public boolean hasLastRenewalTime() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <pre>
       * seconds after the epoch
       * </pre>
       *
       * <code>optional int64 lastRenewalTime = 4;</code>
       * @return The lastRenewalTime.
       */
      @java.lang.Override
      public long getLastRenewalTime() {
        return lastRenewalTime_;
      }
      /**
       * <pre>
       * seconds after the epoch
       * </pre>
       *
       * <code>optional int64 lastRenewalTime = 4;</code>
       * @param value The lastRenewalTime to set.
       * @return This builder for chaining.
       */
      public Builder setLastRenewalTime(long value) {

        lastRenewalTime_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * seconds after the epoch
       * </pre>
       *
       * <code>optional int64 lastRenewalTime = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastRenewalTime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        lastRenewalTime_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:example.Session)
    }

    // @@protoc_insertion_point(class_scope:example.Session)
    private static final com.macasaet.fernet.example.pb.Example.Session DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.macasaet.fernet.example.pb.Example.Session();
    }

    public static com.macasaet.fernet.example.pb.Example.Session getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Session>
        PARSER = new com.google.protobuf.AbstractParser<Session>() {
      @java.lang.Override
      public Session parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Session> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Session> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.macasaet.fernet.example.pb.Example.Session getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_example_Session_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_example_Session_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rexample.proto\022\007example\"^\n\007Session\022\021\n\ts" +
      "essionId\030\001 \002(\t\022\024\n\014renewalCount\030\002 \002(\005\022\021\n\t" +
      "startTime\030\003 \002(\003\022\027\n\017lastRenewalTime\030\004 \001(\003" +
      "B \n\036com.macasaet.fernet.example.pb"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_example_Session_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_example_Session_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_example_Session_descriptor,
        new java.lang.String[] { "SessionId", "RenewalCount", "StartTime", "LastRenewalTime", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
