// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

package com.macasaet.fernet.example.pb;

public final class Example {
  private Example() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SessionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:example.Session)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string sessionId = 1;</code>
     */
    boolean hasSessionId();
    /**
     * <code>required string sessionId = 1;</code>
     */
    java.lang.String getSessionId();
    /**
     * <code>required string sessionId = 1;</code>
     */
    com.google.protobuf.ByteString
        getSessionIdBytes();

    /**
     * <code>required int32 renewalCount = 2;</code>
     */
    boolean hasRenewalCount();
    /**
     * <code>required int32 renewalCount = 2;</code>
     */
    int getRenewalCount();

    /**
     * <pre>
     * seconds after the epoch
     * </pre>
     *
     * <code>required int64 startTime = 3;</code>
     */
    boolean hasStartTime();
    /**
     * <pre>
     * seconds after the epoch
     * </pre>
     *
     * <code>required int64 startTime = 3;</code>
     */
    long getStartTime();

    /**
     * <pre>
     * seconds after the epoch
     * </pre>
     *
     * <code>optional int64 lastRenewalTime = 4;</code>
     */
    boolean hasLastRenewalTime();
    /**
     * <pre>
     * seconds after the epoch
     * </pre>
     *
     * <code>optional int64 lastRenewalTime = 4;</code>
     */
    long getLastRenewalTime();
  }
  /**
   * Protobuf type {@code example.Session}
   */
  public  static final class Session extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:example.Session)
      SessionOrBuilder {
    // Use Session.newBuilder() to construct.
    private Session(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Session() {
      sessionId_ = "";
      renewalCount_ = 0;
      startTime_ = 0L;
      lastRenewalTime_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Session(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              sessionId_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              renewalCount_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              startTime_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              lastRenewalTime_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.macasaet.fernet.example.pb.Example.internal_static_example_Session_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.macasaet.fernet.example.pb.Example.internal_static_example_Session_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.macasaet.fernet.example.pb.Example.Session.class, com.macasaet.fernet.example.pb.Example.Session.Builder.class);
    }

    private int bitField0_;
    public static final int SESSIONID_FIELD_NUMBER = 1;
    private volatile java.lang.Object sessionId_;
    /**
     * <code>required string sessionId = 1;</code>
     */
    public boolean hasSessionId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string sessionId = 1;</code>
     */
    public java.lang.String getSessionId() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sessionId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string sessionId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RENEWALCOUNT_FIELD_NUMBER = 2;
    private int renewalCount_;
    /**
     * <code>required int32 renewalCount = 2;</code>
     */
    public boolean hasRenewalCount() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 renewalCount = 2;</code>
     */
    public int getRenewalCount() {
      return renewalCount_;
    }

    public static final int STARTTIME_FIELD_NUMBER = 3;
    private long startTime_;
    /**
     * <pre>
     * seconds after the epoch
     * </pre>
     *
     * <code>required int64 startTime = 3;</code>
     */
    public boolean hasStartTime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     * seconds after the epoch
     * </pre>
     *
     * <code>required int64 startTime = 3;</code>
     */
    public long getStartTime() {
      return startTime_;
    }

    public static final int LASTRENEWALTIME_FIELD_NUMBER = 4;
    private long lastRenewalTime_;
    /**
     * <pre>
     * seconds after the epoch
     * </pre>
     *
     * <code>optional int64 lastRenewalTime = 4;</code>
     */
    public boolean hasLastRenewalTime() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     * seconds after the epoch
     * </pre>
     *
     * <code>optional int64 lastRenewalTime = 4;</code>
     */
    public long getLastRenewalTime() {
      return lastRenewalTime_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSessionId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRenewalCount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStartTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sessionId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, renewalCount_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, startTime_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, lastRenewalTime_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sessionId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, renewalCount_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, startTime_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, lastRenewalTime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.macasaet.fernet.example.pb.Example.Session)) {
        return super.equals(obj);
      }
      com.macasaet.fernet.example.pb.Example.Session other = (com.macasaet.fernet.example.pb.Example.Session) obj;

      boolean result = true;
      result = result && (hasSessionId() == other.hasSessionId());
      if (hasSessionId()) {
        result = result && getSessionId()
            .equals(other.getSessionId());
      }
      result = result && (hasRenewalCount() == other.hasRenewalCount());
      if (hasRenewalCount()) {
        result = result && (getRenewalCount()
            == other.getRenewalCount());
      }
      result = result && (hasStartTime() == other.hasStartTime());
      if (hasStartTime()) {
        result = result && (getStartTime()
            == other.getStartTime());
      }
      result = result && (hasLastRenewalTime() == other.hasLastRenewalTime());
      if (hasLastRenewalTime()) {
        result = result && (getLastRenewalTime()
            == other.getLastRenewalTime());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSessionId()) {
        hash = (37 * hash) + SESSIONID_FIELD_NUMBER;
        hash = (53 * hash) + getSessionId().hashCode();
      }
      if (hasRenewalCount()) {
        hash = (37 * hash) + RENEWALCOUNT_FIELD_NUMBER;
        hash = (53 * hash) + getRenewalCount();
      }
      if (hasStartTime()) {
        hash = (37 * hash) + STARTTIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getStartTime());
      }
      if (hasLastRenewalTime()) {
        hash = (37 * hash) + LASTRENEWALTIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getLastRenewalTime());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.macasaet.fernet.example.pb.Example.Session parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.macasaet.fernet.example.pb.Example.Session parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.macasaet.fernet.example.pb.Example.Session parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.macasaet.fernet.example.pb.Example.Session parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.macasaet.fernet.example.pb.Example.Session parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.macasaet.fernet.example.pb.Example.Session parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.macasaet.fernet.example.pb.Example.Session parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.macasaet.fernet.example.pb.Example.Session parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.macasaet.fernet.example.pb.Example.Session parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.macasaet.fernet.example.pb.Example.Session parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.macasaet.fernet.example.pb.Example.Session parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.macasaet.fernet.example.pb.Example.Session parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.macasaet.fernet.example.pb.Example.Session prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code example.Session}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:example.Session)
        com.macasaet.fernet.example.pb.Example.SessionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.macasaet.fernet.example.pb.Example.internal_static_example_Session_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.macasaet.fernet.example.pb.Example.internal_static_example_Session_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.macasaet.fernet.example.pb.Example.Session.class, com.macasaet.fernet.example.pb.Example.Session.Builder.class);
      }

      // Construct using com.macasaet.fernet.example.pb.Example.Session.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        sessionId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        renewalCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        startTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        lastRenewalTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.macasaet.fernet.example.pb.Example.internal_static_example_Session_descriptor;
      }

      public com.macasaet.fernet.example.pb.Example.Session getDefaultInstanceForType() {
        return com.macasaet.fernet.example.pb.Example.Session.getDefaultInstance();
      }

      public com.macasaet.fernet.example.pb.Example.Session build() {
        com.macasaet.fernet.example.pb.Example.Session result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.macasaet.fernet.example.pb.Example.Session buildPartial() {
        com.macasaet.fernet.example.pb.Example.Session result = new com.macasaet.fernet.example.pb.Example.Session(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sessionId_ = sessionId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.renewalCount_ = renewalCount_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.startTime_ = startTime_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.lastRenewalTime_ = lastRenewalTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.macasaet.fernet.example.pb.Example.Session) {
          return mergeFrom((com.macasaet.fernet.example.pb.Example.Session)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.macasaet.fernet.example.pb.Example.Session other) {
        if (other == com.macasaet.fernet.example.pb.Example.Session.getDefaultInstance()) return this;
        if (other.hasSessionId()) {
          bitField0_ |= 0x00000001;
          sessionId_ = other.sessionId_;
          onChanged();
        }
        if (other.hasRenewalCount()) {
          setRenewalCount(other.getRenewalCount());
        }
        if (other.hasStartTime()) {
          setStartTime(other.getStartTime());
        }
        if (other.hasLastRenewalTime()) {
          setLastRenewalTime(other.getLastRenewalTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSessionId()) {
          return false;
        }
        if (!hasRenewalCount()) {
          return false;
        }
        if (!hasStartTime()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.macasaet.fernet.example.pb.Example.Session parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.macasaet.fernet.example.pb.Example.Session) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object sessionId_ = "";
      /**
       * <code>required string sessionId = 1;</code>
       */
      public boolean hasSessionId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string sessionId = 1;</code>
       */
      public java.lang.String getSessionId() {
        java.lang.Object ref = sessionId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sessionId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string sessionId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSessionIdBytes() {
        java.lang.Object ref = sessionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sessionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string sessionId = 1;</code>
       */
      public Builder setSessionId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sessionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string sessionId = 1;</code>
       */
      public Builder clearSessionId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sessionId_ = getDefaultInstance().getSessionId();
        onChanged();
        return this;
      }
      /**
       * <code>required string sessionId = 1;</code>
       */
      public Builder setSessionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sessionId_ = value;
        onChanged();
        return this;
      }

      private int renewalCount_ ;
      /**
       * <code>required int32 renewalCount = 2;</code>
       */
      public boolean hasRenewalCount() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 renewalCount = 2;</code>
       */
      public int getRenewalCount() {
        return renewalCount_;
      }
      /**
       * <code>required int32 renewalCount = 2;</code>
       */
      public Builder setRenewalCount(int value) {
        bitField0_ |= 0x00000002;
        renewalCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 renewalCount = 2;</code>
       */
      public Builder clearRenewalCount() {
        bitField0_ = (bitField0_ & ~0x00000002);
        renewalCount_ = 0;
        onChanged();
        return this;
      }

      private long startTime_ ;
      /**
       * <pre>
       * seconds after the epoch
       * </pre>
       *
       * <code>required int64 startTime = 3;</code>
       */
      public boolean hasStartTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       * seconds after the epoch
       * </pre>
       *
       * <code>required int64 startTime = 3;</code>
       */
      public long getStartTime() {
        return startTime_;
      }
      /**
       * <pre>
       * seconds after the epoch
       * </pre>
       *
       * <code>required int64 startTime = 3;</code>
       */
      public Builder setStartTime(long value) {
        bitField0_ |= 0x00000004;
        startTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * seconds after the epoch
       * </pre>
       *
       * <code>required int64 startTime = 3;</code>
       */
      public Builder clearStartTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        startTime_ = 0L;
        onChanged();
        return this;
      }

      private long lastRenewalTime_ ;
      /**
       * <pre>
       * seconds after the epoch
       * </pre>
       *
       * <code>optional int64 lastRenewalTime = 4;</code>
       */
      public boolean hasLastRenewalTime() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <pre>
       * seconds after the epoch
       * </pre>
       *
       * <code>optional int64 lastRenewalTime = 4;</code>
       */
      public long getLastRenewalTime() {
        return lastRenewalTime_;
      }
      /**
       * <pre>
       * seconds after the epoch
       * </pre>
       *
       * <code>optional int64 lastRenewalTime = 4;</code>
       */
      public Builder setLastRenewalTime(long value) {
        bitField0_ |= 0x00000008;
        lastRenewalTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * seconds after the epoch
       * </pre>
       *
       * <code>optional int64 lastRenewalTime = 4;</code>
       */
      public Builder clearLastRenewalTime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        lastRenewalTime_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:example.Session)
    }

    // @@protoc_insertion_point(class_scope:example.Session)
    private static final com.macasaet.fernet.example.pb.Example.Session DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.macasaet.fernet.example.pb.Example.Session();
    }

    public static com.macasaet.fernet.example.pb.Example.Session getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Session>
        PARSER = new com.google.protobuf.AbstractParser<Session>() {
      public Session parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Session(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Session> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Session> getParserForType() {
      return PARSER;
    }

    public com.macasaet.fernet.example.pb.Example.Session getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_example_Session_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_example_Session_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rexample.proto\022\007example\"^\n\007Session\022\021\n\ts" +
      "essionId\030\001 \002(\t\022\024\n\014renewalCount\030\002 \002(\005\022\021\n\t" +
      "startTime\030\003 \002(\003\022\027\n\017lastRenewalTime\030\004 \001(\003" +
      "B \n\036com.macasaet.fernet.example.pb"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_example_Session_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_example_Session_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_example_Session_descriptor,
        new java.lang.String[] { "SessionId", "RenewalCount", "StartTime", "LastRenewalTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
